import * as THREE from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const canvas=document.querySelector('#space'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x010207);const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,3000);camera.position.set(0,105,175);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.045;controls.minDistance=12;controls.maxDistance=420;controls.target.set(0,0,0);
// Dense layered star field.
function stars(count,radius,size,opacity){const g=new THREE.BufferGeometry(),p=new Float32Array(count*3);for(let i=0;i<count;i++){const r=radius*(.45+Math.random()*.55),a=Math.random()*Math.PI*2,z=Math.random()*2-1,s=Math.sqrt(1-z*z);p[i*3]=r*s*Math.cos(a);p[i*3+1]=r*z;p[i*3+2]=r*s*Math.sin(a)}g.setAttribute('position',new THREE.BufferAttribute(p,3));const m=new THREE.PointsMaterial({color:0xffffff,size,transparent:true,opacity,sizeAttenuation:true});scene.add(new THREE.Points(g,m))}stars(6500,900,.55,.72);stars(900,650,1.25,.85);
// Sun with layered glow sprites.
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,0,128,128,128);g.addColorStop(0,'rgba(255,255,240,1)');g.addColorStop(.12,'rgba(255,210,90,.9)');g.addColorStop(.35,'rgba(255,120,25,.28)');g.addColorStop(1,'rgba(255,80,0,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c)}const sun=new THREE.Mesh(new THREE.SphereGeometry(7,64,64),new THREE.MeshBasicMaterial({color:0xffcc72}));scene.add(sun);const sg=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture(),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));sg.scale.set(38,38,1);sun.add(sg);const light=new THREE.PointLight(0xfff1d2,2600,700,1.2);scene.add(light);scene.add(new THREE.AmbientLight(0x18223d,.16));
const data=[
{name:'Mercury',type:'TERRESTRIAL PLANET',color:0x9b938a,size:1.15,a:13,period:88,rot:58.6,moons:0,desc:'The smallest planet and the fastest world around the Sun, marked by a heavily cratered surface.'},
{name:'Venus',type:'TERRESTRIAL PLANET',color:0xd9a85d,size:1.75,a:19,period:224.7,rot:-243,moons:0,desc:'A cloud-covered world with a dense atmosphere and the hottest planetary surface in the Solar System.'},
{name:'Earth',type:'TERRESTRIAL PLANET',color:0x397cc9,size:1.85,a:26,period:365.256,rot:1,moons:1,desc:'Our ocean world. Sunlight creates a continuously moving day-night boundary as Earth rotates.'},
{name:'Mars',type:'TERRESTRIAL PLANET',color:0xb94e32,size:1.45,a:34,period:687,rot:1.026,moons:2,desc:'A cold desert world of iron-rich plains, giant volcanoes, deep canyons and two small moons.'},
{name:'Jupiter',type:'GAS GIANT',color:0xc89d76,size:4.8,a:48,period:4332.6,rot:.414,moons:95,desc:'The largest planet, a turbulent gas giant with powerful storms and a vast family of moons.'},
{name:'Saturn',type:'GAS GIANT',color:0xd7bd7c,size:4.15,a:64,period:10759,rot:.444,moons:146,desc:'A pale gas giant surrounded by the most spectacular and complex ring system in our Solar System.',ring:true},
{name:'Uranus',type:'ICE GIANT',color:0x8fd4da,size:2.9,a:80,period:30687,rot:-.718,moons:28,desc:'An ice giant rotating almost on its side, with a muted blue-green atmosphere rich in methane.'},
{name:'Neptune',type:'ICE GIANT',color:0x3159b8,size:2.8,a:96,period:60190,rot:.671,moons:16,desc:'The distant blue ice giant, home to some of the fastest winds measured anywhere in the Solar System.'}
];
const planets=[],raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),epoch=new Date('2026-01-01T00:00:00Z');
function orbitLine(r){const pts=[];for(let i=0;i<=160;i++){const a=i/160*Math.PI*2;pts.push(new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r))}const g=new THREE.BufferGeometry().setFromPoints(pts);scene.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:0x42506b,transparent:true,opacity:.22})))}
function earthMaterial(){return new THREE.MeshStandardMaterial({color:0x2c70b7,roughness:.75,metalness:0,emissive:0x06111f,emissiveIntensity:.5})}
data.forEach((d,i)=>{orbitLine(d.a);const pivot=new THREE.Group();scene.add(pivot);const mat=d.name==='Earth'?earthMaterial():new THREE.MeshStandardMaterial({color:d.color,roughness:.82,metalness:0});const mesh=new THREE.Mesh(new THREE.SphereGeometry(d.size,48,48),mat);mesh.userData={...d,index:i};pivot.add(mesh);if(d.ring){const ring=new THREE.Mesh(new THREE.RingGeometry(d.size*1.35,d.size*2.15,96),new THREE.MeshStandardMaterial({color:0xb9a47d,side:THREE.DoubleSide,transparent:true,opacity:.65,roughness:1}));ring.rotation.x=Math.PI/2.25;mesh.add(ring)}if(d.name==='Earth'){const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(d.size*1.055,48,48),new THREE.MeshBasicMaterial({color:0x65b8ff,transparent:true,opacity:.11,side:THREE.BackSide,blending:THREE.AdditiveBlending}));mesh.add(atmosphere);const cityGeo=new THREE.BufferGeometry(),arr=[];for(let k=0;k<170;k++){const phi=Math.acos(2*Math.random()-1),theta=Math.random()*Math.PI*2,r=d.size*1.008;arr.push(r*Math.sin(phi)*Math.cos(theta),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(theta))}cityGeo.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));mesh.add(new THREE.Points(cityGeo,new THREE.PointsMaterial({color:0xffc36a,size:.035,transparent:true,opacity:.85})))}const label=document.createElement('div');label.className='planet-label';label.textContent=d.name;document.querySelector('#labels').appendChild(label);planets.push({d,pivot,mesh,label})});
let offset=0,playing=true,speed=1,selected=null,last=performance.now();const dateLabel=document.querySelector('#dateLabel'),range=document.querySelector('#timeRange');
function simDate(){const d=new Date();d.setDate(d.getDate()+offset);return d}function updateDate(){dateLabel.textContent=simDate().toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase();range.value=Math.max(-3650,Math.min(3650,offset))}
function updatePlanets(){const days=(simDate()-epoch)/86400000;planets.forEach((p,i)=>{const phase=i*.72+.35,ang=phase+days/p.d.period*Math.PI*2;p.mesh.position.set(Math.cos(ang)*p.d.a,Math.sin(i*.7)*.22,Math.sin(ang)*p.d.a);p.mesh.rotation.y=days/p.d.rot*Math.PI*2;const v=p.mesh.getWorldPosition(new THREE.Vector3()).project(camera);p.label.style.left=(v.x*.5+.5)*innerWidth+'px';p.label.style.top=(-v.y*.5+.5)*innerHeight+'px';p.label.style.opacity=v.z<1&&!selected?Math.max(.2,1-Math.abs(v.z)*.4):0})}
function selectPlanet(mesh){selected=mesh;const d=mesh.userData;document.querySelector('#intro').classList.add('hidden');document.querySelector('#planetPanel').classList.add('open');planetType.textContent=d.type;planetName.textContent=d.name;planetDesc.textContent=d.desc;day.textContent=Math.abs(d.rot)<2?(Math.abs(d.rot)*24).toFixed(1)+' HOURS':Math.abs(d.rot).toFixed(1)+' DAYS';year.textContent=d.period<1000?Math.round(d.period)+' DAYS':(d.period/365.256).toFixed(1)+' YEARS';distance.textContent=(d.a/26*149.6).toFixed(0)+'M KM';moons.textContent=d.moons;controls.enabled=false}
function reset(){selected=null;document.querySelector('#intro').classList.remove('hidden');document.querySelector('#planetPanel').classList.remove('open');controls.enabled=true;controls.target.set(0,0,0);camera.position.set(0,105,175)}closePlanet.onclick=reset;resetView.onclick=reset;
canvas.addEventListener('pointerdown',e=>{mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(planets.map(p=>p.mesh),false);if(hits.length)selectPlanet(hits[0].object)});
range.oninput=e=>{offset=+e.target.value;playing=false;play.textContent='▶';updateDate()};today.onclick=()=>{offset=0;playing=true;play.textContent='Ⅱ';updateDate()};play.onclick=()=>{playing=!playing;play.textContent=playing?'Ⅱ':'▶'};document.querySelector('#speed').onchange=e=>speed=+e.target.value;
// Apple-Watch-like bottom pointer time scrubbing: hold Shift and move horizontally anywhere, or move along the timeline while dragging.
let scrub=false,lastX=0;addEventListener('pointerdown',e=>{if(e.clientY>innerHeight-125){scrub=true;lastX=e.clientX}});addEventListener('pointerup',()=>scrub=false);addEventListener('pointermove',e=>{if(scrub||e.shiftKey){const dx=e.clientX-lastX;offset+=dx*1.6;lastX=e.clientX;playing=false;play.textContent='▶';updateDate()}});
function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-last)/1000,.05);last=t;if(playing){offset+=dt*speed*.08;updateDate()}updatePlanets();if(selected){const pos=selected.getWorldPosition(new THREE.Vector3()),s=selected.userData.size;const desired=pos.clone().add(new THREE.Vector3(s*1.5,s*.8,s*4.2));camera.position.lerp(desired,.045);controls.target.lerp(pos,.07);camera.lookAt(controls.target)}else controls.update();sun.rotation.y+=dt*.03;renderer.render(scene,camera)}updateDate();animate(performance.now());addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});