import * as THREE from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id),canvas=$('space'),renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x010207);const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,3000);camera.position.set(0,105,175);const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.045;controls.minDistance=12;controls.maxDistance=420;controls.target.set(0,0,0);
function stars(count,radius,size,opacity){const g=new THREE.BufferGeometry(),p=new Float32Array(count*3);for(let i=0;i<count;i++){const r=radius*(.45+Math.random()*.55),a=Math.random()*Math.PI*2,z=Math.random()*2-1,s=Math.sqrt(1-z*z);p[i*3]=r*s*Math.cos(a);p[i*3+1]=r*z;p[i*3+2]=r*s*Math.sin(a)}g.setAttribute('position',new THREE.BufferAttribute(p,3));scene.add(new THREE.Points(g,new THREE.PointsMaterial({color:0xffffff,size,transparent:true,opacity,sizeAttenuation:true})))}stars(6500,900,.55,.72);stars(900,650,1.25,.85);
function glowTexture(){const c=document.createElement('canvas');c.width=c.height=256;const x=c.getContext('2d'),g=x.createRadialGradient(128,128,0,128,128,128);g.addColorStop(0,'rgba(255,255,240,1)');g.addColorStop(.12,'rgba(255,210,90,.9)');g.addColorStop(.35,'rgba(255,120,25,.28)');g.addColorStop(1,'rgba(255,80,0,0)');x.fillStyle=g;x.fillRect(0,0,256,256);return new THREE.CanvasTexture(c)}const sun=new THREE.Mesh(new THREE.SphereGeometry(7,64,64),new THREE.MeshBasicMaterial({color:0xffcc72}));scene.add(sun);const sg=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTexture(),transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));sg.scale.set(38,38,1);sun.add(sg);scene.add(new THREE.PointLight(0xfff1d2,2600,700,1.2));scene.add(new THREE.AmbientLight(0x18223d,.12));
// Approximate J2000 orbital elements. Distances are visually compressed, but eccentricity, inclination and date-dependent motion are preserved.
const data=[
{name:'Mercury',type:'TERRESTRIAL PLANET',color:0x9b938a,size:1.15,a:13,e:.2056,inc:7.005,node:48.33,peri:29.12,period:87.969,phase:174.8,rot:58.6,moons:0,desc:'The smallest planet and the fastest world around the Sun, marked by a heavily cratered surface.'},
{name:'Venus',type:'TERRESTRIAL PLANET',color:0xd9a85d,size:1.75,a:19,e:.0068,inc:3.394,node:76.68,peri:54.85,period:224.701,phase:50.4,rot:-243,moons:0,desc:'A cloud-covered world with a dense atmosphere and the hottest planetary surface in the Solar System.'},
{name:'Earth',type:'TERRESTRIAL PLANET',color:0x397cc9,size:1.85,a:26,e:.0167,inc:0,node:-11.26,peri:114.21,period:365.256,phase:357.5,rot:.9973,moons:1,desc:'Our ocean world. Sunlight creates a continuously moving day-night boundary as Earth rotates.'},
{name:'Mars',type:'TERRESTRIAL PLANET',color:0xb94e32,size:1.45,a:34,e:.0934,inc:1.85,node:49.56,peri:286.5,period:686.98,phase:19.4,rot:1.026,moons:2,desc:'A cold desert world of iron-rich plains, giant volcanoes, deep canyons and two small moons.'},
{name:'Jupiter',type:'GAS GIANT',color:0xc89d76,size:4.8,a:48,e:.0489,inc:1.303,node:100.46,peri:273.87,period:4332.59,phase:20,rot:.414,moons:95,desc:'The largest planet, a turbulent gas giant with powerful storms and a vast family of moons.'},
{name:'Saturn',type:'GAS GIANT',color:0xd7bd7c,size:4.15,a:64,e:.0565,inc:2.485,node:113.67,peri:339.39,period:10759.22,phase:317,rot:.444,moons:146,desc:'A pale gas giant surrounded by the most spectacular and complex ring system in our Solar System.',ring:true},
{name:'Uranus',type:'ICE GIANT',color:0x8fd4da,size:2.9,a:80,e:.0457,inc:.773,node:74.01,peri:96.99,period:30688.5,phase:142,rot:-.718,moons:28,desc:'An ice giant rotating almost on its side, with a muted blue-green atmosphere rich in methane.'},
{name:'Neptune',type:'ICE GIANT',color:0x3159b8,size:2.8,a:96,e:.0113,inc:1.77,node:131.78,peri:273.19,period:60182,phase:256,rot:.671,moons:16,desc:'The distant blue ice giant, home to some of the fastest winds measured anywhere in the Solar System.'}];
const DEG=Math.PI/180,planets=[],raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),epoch=new Date('2000-01-01T12:00:00Z');
function orbitalPosition(d,days){let M=(d.phase*DEG+days/d.period*Math.PI*2)%(Math.PI*2),E=M;for(let j=0;j<7;j++)E=M+d.e*Math.sin(E);const x=d.a*(Math.cos(E)-d.e),z=d.a*Math.sqrt(1-d.e*d.e)*Math.sin(E),v=new THREE.Vector3(x,0,z);v.applyAxisAngle(new THREE.Vector3(0,1,0),d.peri*DEG);v.applyAxisAngle(new THREE.Vector3(0,0,1),d.inc*DEG);v.applyAxisAngle(new THREE.Vector3(0,1,0),d.node*DEG);return v}
function orbitLine(d){const pts=[];for(let i=0;i<=180;i++){const fake=i/180*d.period;pts.push(orbitalPosition({...d,phase:0},fake))}scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0x42506b,transparent:true,opacity:.22})))}
data.forEach((d,i)=>{orbitLine(d);const mat=new THREE.MeshStandardMaterial({color:d.color,roughness:.82,metalness:0,emissive:d.name==='Earth'?0x020913:0x000000,emissiveIntensity:.25});const mesh=new THREE.Mesh(new THREE.SphereGeometry(d.size,56,56),mat);mesh.userData={...d,index:i};scene.add(mesh);if(d.ring){const ring=new THREE.Mesh(new THREE.RingGeometry(d.size*1.35,d.size*2.15,128),new THREE.MeshStandardMaterial({color:0xb9a47d,side:THREE.DoubleSide,transparent:true,opacity:.68,roughness:1}));ring.rotation.x=Math.PI/2.25;mesh.add(ring)}if(d.name==='Earth'){mesh.rotation.z=23.44*DEG;const atmosphere=new THREE.Mesh(new THREE.SphereGeometry(d.size*1.055,56,56),new THREE.MeshBasicMaterial({color:0x65b8ff,transparent:true,opacity:.13,side:THREE.BackSide,blending:THREE.AdditiveBlending}));mesh.add(atmosphere)}const label=document.createElement('div');label.className='planet-label';label.textContent=d.name;$('labels').appendChild(label);planets.push({d,mesh,label})});
let offset=0,playing=true,speed=1,selected=null,last=performance.now(),scrub=false,lastX=0,focusReady=false;const range=$('timeRange');function simDate(){return new Date(Date.now()+offset*86400000)}function updateDate(){const d=simDate();$('dateLabel').textContent=d.toLocaleDateString('en-US',{day:'2-digit',month:'short',year:'numeric'}).toUpperCase();range.value=Math.max(-3650,Math.min(3650,Math.round(offset)))}
function updatePlanets(){const days=(simDate()-epoch)/86400000;planets.forEach(p=>{p.mesh.position.copy(orbitalPosition(p.d,days));p.mesh.rotation.y=days/p.d.rot*Math.PI*2;const v=p.mesh.getWorldPosition(new THREE.Vector3()).project(camera),visible=v.z>-1&&v.z<1&&!selected;p.label.style.left=(v.x*.5+.5)*innerWidth+'px';p.label.style.top=(-v.y*.5+.5)*innerHeight+'px';p.label.style.opacity=visible?'1':'0'})}
function selectPlanet(mesh){selected=mesh;focusReady=false;const d=mesh.userData;$('intro').classList.add('hidden');$('planetPanel').classList.add('open');$('planetType').textContent=d.type;$('planetName').textContent=d.name;$('planetDesc').textContent=d.desc;$('day').textContent=Math.abs(d.rot)<2?(Math.abs(d.rot)*24).toFixed(1)+' HOURS':Math.abs(d.rot).toFixed(1)+' DAYS';$('year').textContent=d.period<1000?Math.round(d.period)+' DAYS':(d.period/365.256).toFixed(1)+' YEARS';$('distance').textContent=(d.a/26*149.6).toFixed(0)+'M KM';$('moons').textContent=d.moons;controls.enabled=true;controls.minDistance=d.size*2.2;controls.maxDistance=d.size*15}
function reset(){selected=null;focusReady=false;$('intro').classList.remove('hidden');$('planetPanel').classList.remove('open');controls.enabled=true;controls.minDistance=12;controls.maxDistance=420;controls.target.set(0,0,0);camera.position.set(0,105,175)}$('closePlanet').onclick=reset;$('resetView').onclick=reset;
canvas.addEventListener('click',e=>{mouse.x=e.clientX/innerWidth*2-1;mouse.y=-(e.clientY/innerHeight)*2+1;raycaster.setFromCamera(mouse,camera);const hits=raycaster.intersectObjects(planets.map(p=>p.mesh),false);if(hits.length)selectPlanet(hits[0].object)});range.oninput=e=>{offset=+e.target.value;playing=false;$('play').textContent='▶';updateDate()};$('today').onclick=()=>{offset=0;playing=true;$('play').textContent='Ⅱ';updateDate()};$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ':'▶'};$('speed').onchange=e=>speed=+e.target.value;
// Bottom-zone mouse time travel: click/drag horizontally to scrub dates. Shift+move also works anywhere.
addEventListener('pointerdown',e=>{if(e.clientY>innerHeight-145){scrub=true;lastX=e.clientX}});addEventListener('pointerup',()=>scrub=false);addEventListener('pointercancel',()=>scrub=false);addEventListener('pointermove',e=>{if(scrub||e.shiftKey){if(!lastX)lastX=e.clientX;const dx=e.clientX-lastX;offset+=dx*1.4;lastX=e.clientX;playing=false;$('play').textContent='▶';updateDate()}else lastX=e.clientX});
function animate(t){requestAnimationFrame(animate);const dt=Math.min((t-last)/1000,.05);last=t;if(playing){offset+=dt*speed*.08;updateDate()}updatePlanets();if(selected){const pos=selected.getWorldPosition(new THREE.Vector3()),s=selected.userData.size;controls.target.lerp(pos,.12);if(!focusReady){const direction=camera.position.clone().sub(pos).normalize();if(direction.lengthSq()<.1)direction.set(0,.2,1);const desired=pos.clone().add(direction.multiplyScalar(s*5.5)).add(new THREE.Vector3(0,s*.7,0));camera.position.lerp(desired,.065);if(camera.position.distanceTo(desired)<s*.3)focusReady=true}controls.update()}else controls.update();sun.rotation.y+=dt*.03;renderer.render(scene,camera)}updateDate();animate(performance.now());addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});